plugins {
    id 'com.android.application'
}

android {
    namespace 'com.byso.jetpakquote'
    compileSdk 35

    defaultConfig {
        applicationId 'com.byso.jetpakquote'
        minSdk 24
        targetSdk 35
        versionCode 6
        versionName '1.5.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
